### ISSUE TITLE
libsvtav1 conflicts with other libraries in ffmpeg. Does not run unless they are disabled.

### ISSUE THREAD

**Issue by moisespr123** [OpenVisualCloud/SVT-AV1#567]
Hi,

I've been trying to get `libsvtav1` to run on ffmpeg built using the `media-autobuild-suite` build script. 

While it does compiles, it turns out that `libsvtav1` conflicts with `libopencore-amrwb`, `libsvthevc` and `libaom`. Disabling these libraries makes `libsvtav1` encode a video successfully.

## Conflict with `libopencore-amrwb`:
```
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbIntraPrediction.c.obj): warning: common of `pred' overridden by definition from H:/repos/media-autobuild_suite/msys64/mingw64/lib/libopencore-amrwb.a(dec_gain2_amr_wb.o)
collect2.exe: error: ld returned 1 exit status
```

## Conflict with `libsvthevc`:
```
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x0): multiple definition of `MdcRefinement'; H:/repos/media-autobuild_suite/local64/lib/libSvtHevcEnc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x0): first defined here
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x570): multiple definition of `RefinementPredictionLoop'; H:/repos/media-autobuild_suite/local64/lib/libSvtHevcEnc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x7a0): first defined here
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x770): multiple definition of `ForwardCuToModeDecision'; H:/repos/media-autobuild_suite/local64/lib/libSvtHevcEnc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0xc30): first defined here
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x9c0): multiple definition of `MdcInterDepthDecision'; H:/repos/media-autobuild_suite/local64/lib/libSvtHevcEnc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0xe50): first defined here
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0xbd0): multiple definition of `PredictionPartitionLoop'; H:/repos/media-autobuild_suite/local64/lib/libSvtHevcEnc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x1110): first defined here
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.rdata+0x0): multiple definition of `incrementalCount'; H:/repos/media-autobuild_suite/local64/lib/libSvtHevcEnc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.rdata+0x0): first defined here
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbMotionEstimationContext.c.obj):EbMotionEstimationContext.c:(.text+0x130): multiple definition of `MotionEstimetionPredUnitCtor'; H:/repos/media-autobuild_suite/local64/lib/libSvtHevcEnc.a(EbMotionEstimationContext.c.obj):EbMotionEstimationContext.c:(.text+0x0): first defined here
make: *** [/build/ffmpeg-git/Makefile:111: ffmpeg_g.exe] Error 1
```

## Conflict with `libaom`:
```
Likely error:
D:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(convolve_avx2.c.obj):convolve_avx2.c:(.text+0xc90): multiple definition of `av1_build_compound_diffwtd_mask_d16_avx2'; D:/repos/media-autobuild_suite/local64/lib/libaom.a(reconinter_avx2.c.o):reconinter_avx2.c:(.text+0x350): first defined here
D:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(convolve_avx2.c.obj):convolve_avx2.c:(.text+0x1cc0): multiple definition of `av1_wedge_sse_from_residuals_avx2'; D:/repos/media-autobuild_suite/local64/lib/libaom.a(wedge_utils_avx2.c.o):wedge_utils_avx2.c:(.text+0x0): first defined here
D:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(convolve_avx2.c.obj):convolve_avx2.c:(.text+0x1da0): multiple definition of `aom_subtract_block_avx2'; D:/repos/media-autobuild_suite/local64/lib/libaom.a(subtract_avx2.c.o):subtract_avx2.c:(.text+0x0): first defined here
D:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(convolve_avx2.c.obj):convolve_avx2.c:(.text+0x20f0): multiple definition of `aom_sse_avx2'; D:/repos/media-autobuild_suite/local64/lib/libaom.a(sse_avx2.c.o):sse_avx2.c:(.text+0x0): first defined here
D:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(convolve_avx2.c.obj):convolve_avx2.c:(.text+0x27d0): multiple definition of `aom_lowbd_blend_a64_d16_mask_avx2'; D:/repos/media-autobuild_suite/local64/lib/libaom.a(blend_a64_mask_avx2.c.o):blend_a64_mask_avx2.c:(.text+0x0): first defined here
D:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(convolve_avx2.c.obj):convolve_avx2.c:(.text+0x37a0): multiple definition of `aom_sum_squares_i16_sse2'; D:/repos/media-autobuild_suite/local64/lib/libaom.a(sum_squares_sse2.c.o):sum_squares_sse2.c:(.text+0x410): first defined here
D:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(convolve_avx2.c.obj):convolve_avx2.c:(.text+0x3810): multiple definition of `av1_wedge_sign_from_residuals_avx2'; D:/repos/media-autobuild_suite/local64/lib/libaom.a(wedge_utils_avx2.c.o):wedge_utils_avx2.c:(.text+0xe0): first defined here
D:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(convolve_avx2.c.obj):convolve_avx2.c:(.text+0x3910): multiple definition of `av1_wedge_compute_delta_squares_avx2'; D:/repos/media-autobuild_suite/local64/lib/libaom.a(wedge_utils_avx2.c.o):wedge_utils_avx2.c:(.text+0x1e0): first defined here
```

**Comment by xuguangxin** [comment]
the libaom issue is a newly introduced issue. I have fixed this before through https://github.com/OpenVisualCloud/SVT-AV1/commit/6dc355b218d3040177833ab73a347792dfb39dc5
After we fixed this issue again, is it possible to add this library to ci? It will avoid future build fail.
@hassount @kylophone

**Comment by ksuhiyp** [comment]
I can confirm that libsvtav1 conflicts with libaom in ffmpeg, when trying to work with libav1st ffmpeg segfaults form the 1 frame

**Comment by xuguangxin** [comment]
@ksuhiyp @moisespr123 , I tried the latest build, it seems we do not have this problem anymore. 
could you double-check it?
If you still can reproduce this, could you share some steps?

thanks

**Comment by 1480c1** [comment]
> @ksuhiyp @moisespr123 , I tried the latest build, it seems we do not have this problem anymore.
> could you double-check it?
> If you still can reproduce this, could you share some steps?
> 
> thanks

Make sure you are using static libraries and not shared libraries

**Comment by grill05** [comment]
@xuguangxin @1480c1 I just tested with git master svt/libaom/ffmpeg and the problem is still there. libaom was compiled with `cmake ../aom -DBUILD_SHARED_LIBS=1`
SVT-AV1 was built with all defaults (just `bash build.sh`)
`--enable-libaom` and `--enable-libsvtav1` were given as options for ffmpeg `configure`
To test, I run
`ffmpeg -i test.mkv -c:v libsvt_av1 out.svt.mkv`
and this gives
```
Press [q] to stop, [?] for help
SVT [version]:  SVT-AV1 Encoder Lib v0.7.0
SVT [build]  :  GCC 9.1.0        64 bit
LIB Build date: Nov 21 2019 21:37:37
-------------------------------------------
Segmentation fault (core dumped)
```

**Comment by 1480c1** [comment]
I mean static libaom and static libSvtAv1Enc

**Comment by moisespr123** [comment]
Still not working.

Multiple definitions messages:

```
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbGlobalMotionEstimationCost.c.obj):EbGlobalMotionEstimationCost.c:(.text+0x0): multiple definition of `aom_count_signed_primitive_refsubexpfin'; H:/repos/media-autobuild_suite/local64/lib/libaom.a(binary_codes_writer.c.o):binary_codes_writer.c:(.text+0x630): first defined here
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x0): multiple definition of `MdcRefinement'; H:/repos/media-autobuild_suite/local64/lib/libSvtHevcEnc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x0): first defined here
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x570): multiple definition of `RefinementPredictionLoop'; H:/repos/media-autobuild_suite/local64/lib/libSvtHevcEnc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x7e0): first defined here
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x770): multiple definition of `ForwardCuToModeDecision'; H:/repos/media-autobuild_suite/local64/lib/libSvtHevcEnc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0xcb0): first defined here
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x9c0): multiple definition of `MdcInterDepthDecision'; H:/repos/media-autobuild_suite/local64/lib/libSvtHevcEnc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0xed0): first defined here
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x38d0): multiple definition of `PredictionPartitionLoop'; H:/repos/media-autobuild_suite/local64/lib/libSvtHevcEnc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x11a0): first defined here
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.rdata+0x20): multiple definition of `incrementalCount'; H:/repos/media-autobuild_suite/local64/lib/libSvtHevcEnc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.rdata+0x0): first defined here
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbMotionEstimationContext.c.obj):EbMotionEstimationContext.c:(.text+0x130): multiple definition of `MotionEstimetionPredUnitCtor'; H:/repos/media-autobuild_suite/local64/lib/libSvtHevcEnc.a(EbMotionEstimationContext.c.obj):EbMotionEstimationContext.c:(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
```

**Comment by xuguangxin** [comment]
@moisespr123 , I can't reproduce your issue on Linux.
maybe ti's related to mingw.

@1480c1 I can reproduce the issue if I set both libaom and libsvt as static.
But, even I removed libsvtav1, ffmpeg still can't link static libaom. it will report the following issue.
Do you know how to work around it firstly?

> /usr/bin/ld: /myopt/codecs/vaapi/lib/libaom.a(noise_model.c.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: final link failed: Bad value
> collect2: error: ld returned 1 exit status
> ffbuild/library.mak:102: recipe for target 'libavcodec/libavcodec.so.58' failed


my build command is

> ./configure --enable-libaom

**Comment by 1480c1** [comment]
```dockerfile
FROM ubuntu:19.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y -q --no-install-recommends build-essential git cmake ca-certificates pkg-config nasm yasm autoconf automake libtool

RUN git clone https://git.code.sf.net/p/opencore-amr/code opencore-amr && \
    cd opencore-amr && autoreconf -fiv && \
    mkdir build-static && cd build-static && \
    ../configure --enable-static --disable-shared && \
    make -j $(nproc) install

RUN git clone https://aomedia.googlesource.com/aom && \
    mkdir aom/build-static && cd aom/build-static && \
    cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF -DENABLE_TESTS=0 && \
    make -j $(nproc) install

RUN git clone https://github.com/OpenVisualCloud/SVT-HEVC.git && \
    mkdir SVT-HEVC/build-static && cd SVT-HEVC/build-static && \
    cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF && \
    make -j $(nproc) install

RUN git clone https://github.com/OpenVisualCloud/SVT-AV1.git && \
    mkdir SVT-AV1/build-static && cd SVT-AV1/build-static && \
    cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF && \
    make -j $(nproc) install

RUN git clone https://github.com/FFmpeg/FFmpeg.git && \
    cd FFmpeg && \
    git apply /SVT-HEVC/ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch && \
    git apply /SVT-AV1/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch && \
    mkdir build-static && cd build-static && \
    ../configure --enable-version3 --enable-libopencore-amrwb --enable-libaom --enable-libsvthevc --enable-libsvtav1 && \
    make -j $(nproc) install
```

```bash
docker build . # With the above copied and pasted into a file called `Dockerfile` in .
```
dockerfile for a reproducible build

If you want to test it on your local machine, run only the parts after `RUN`

**Comment by 1480c1** [comment]
> @1480c1 I can reproduce the issue if I set both libaom and libsvt as static.
> But, even I removed libsvtav1, ffmpeg still can't link static libaom. it will report the following issue.
> Do you know how to work around it firstly?
> 
> > /usr/bin/ld: /myopt/codecs/vaapi/lib/libaom.a(noise_model.c.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
> > /usr/bin/ld: final link failed: Bad value
> > collect2: error: ld returned 1 exit status
> > ffbuild/library.mak:102: recipe for target 'libavcodec/libavcodec.so.58' failed

Delete your libaom build folder and rebuild shared or don't build ffmpeg shared(`--disable-shared`)

You are trying to make a shared lib with `-fPIC` with object files (in the archive) that were not compiled with `-fPIC`

**Comment by grill05** [comment]
I've created a script for linux/macos that will build a static ffmpeg with the latest libx265+libaom+libsvt-av1. T
The auto-build script is at https://gist.github.com/grill05/4dff067220f65eea93a83a20e0fe683d
It has a bunch of other encoders (you can see details in the script)
I adapted my script from here https://github.com/markus-perl/ffmpeg-build-script
Once this build issue is resolved, this script will allow building a single static binary that contains most encoders (libaom-git/svt-git/libx264/libx265-git/libopus/mp3) etc
The svt portion is disabled (commented out) for now because  of this build issue 
@1480c1

**Comment by grill05** [comment]
@xuguangxin I got exactly the same error as well. I was trying to build static-libaom+static-libsvt and link it to a static-ffmpeg binary.
To solve this aom error, I did
`cmake -DCONFIG_PIC=1`
when configuring libaom. And then the compile+linking worked okay.

This maybe related to `-fPIC` that 1480c1 mentioned

**Comment by 1480c1** [comment]
https://pastebin.com/QQQ9CzFe

Latest log from trying to build using https://github.com/OpenVisualCloud/SVT-AV1/issues/567#issuecomment-558662035

**Comment by ePirat** [comment]
So basically a good way to ensure those conflicts do not happen would be to prefix all functions copied from libaom with something like `svt_aom_` or so. As long as it's done consistently it should be easy to adapt new code copied from aom?

For types or defines it does not matter that much, as long as you ensure none of these end up in the public SVT-AV1 API. 

It might be useful to add a script to CI to ensure only `svt_av1_` prefixed (or whatever other prefix is decided on) functions are in the public headers?

**Comment by xuguangxin** [comment]
@moisespr123 could you try https://github.com/OpenVisualCloud/SVT-AV1/pull/1329?

thanks

**Comment by xuguangxin** [comment]
@moisespr123 any luck to try https://github.com/OpenVisualCloud/SVT-AV1/pull/1329?
thanks
